ali:
  accessKeyId: LTAI0CIiXOnd3SNK
  accessKeySecret: tMvvZ3VELyPWYfbk8hYNwFCnnTXk2j
  sms:
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    signName: 陈瑶
    templateCode: SMS_115930654
  mail:
    accountName: panpan@dream-yao.top
    tagName: chenyao
    fromAlias: 私律科技
    subject: 登陆验证码